// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ImgHzw: typeof import('./src/components/img-hzw/ImgHzw.vue')['default']
    ProductCard: typeof import('./src/components/product-card/ProductCard.vue')['default']
    PromotionPopup: typeof import('./src/components/promotion-popup/PromotionPopup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanField: typeof import('vant/es')['Field']
    VanImage: typeof import('vant/es')['Image']
    VanPopup: typeof import('vant/es')['Popup']
    VanStep: typeof import('vant/es')['Step']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSteps: typeof import('vant/es')['Steps']
  }
}
